apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-finance
  labels:
    app: banking-finance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-finance
  template:
    metadata:
      labels:
        app: banking-finance
    spec:
      containers:
      - name: banking-finance-container
        image: preddy1725/banking-finance
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: banking-finance-nodeport-service
  labels:
    app: banking-finance
spec:
  selector:
    app: banking-finance

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8081
    targetPort: 8081
